#ifndef TRU_OPTIONS_H
#define TRU_OPTIONS_H

#define TRU_TARGET_C5SOC   0
#define TRU_TARGET_STM32H7 1

#define TRU_CPU_FAMILY_CORTEXA9 0
#define TRU_CPU_FAMILY_CORTEXM7 1

#define TRU_BOARD_CUSTOM          0
#define TRU_BOARD_C5SOC_CUSTOM    1
#define TRU_BOARD_DE10NANO        2
#define TRU_BOARD_STM32H7_CUSTOM  3
#define TRU_BOARD_NUCLEO144_753ZI 4

#endif
