/*
	Copyright (c) 2023 Truong Hy

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#ifndef IRQ_C5SOC_H
#define IRQ_C5SOC_H

#include <stdint.h>

#define IRQ_GIC_LINE_COUNT 256U
#define IRQ_GIC_EXTERN_IRQ_TABLE
#define IRQHANDLER_T
typedef void (*IRQHandler_t) (void);

#include "irq_ctrl.h"

// Interrupt priority grouping
// ===========================
// Interrupt priorities is set by two values, group-priority and sub-priority.
// The number of bits allocated to each is a split of 8-bits, which is
// controlled by the low 3-bits of the GICC_BPR register called binary point
// value.
//	 	 See https://developer.arm.com/documentation/ihi0048/b/Interrupt-Handling-and-Prioritization/Interrupt-prioritization/Priority-grouping?lang=en
// On Cyclone V HPS (Arm Cortex-A9), the binary point value is defaulted to 2,
// which is also the maximum split for this CPU.  For group 0 interrupt, this
// sets a split of 5 bits allocated for the group-priority, giving 32
// group-priority levels, and 3 bits allocated for the sub-priority, giving 8
// sub-priority levels.  The split or binary point value can be changed by
// calling IRQ_SetPriorityGroupBits().

// Note, Arm defines the priority order with higher value = lower priority, so
// 0 is highest.  With a group priority of 5 bits, priority 31 is the lowest
// priority (all 1s), however, this value is set aside for the IRQ CPU
// priority mask, so cannot be used, the lowest useable group-priority
// is one less, i.e. 30.
#define GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(grp, sub) (((unsigned char)grp << 3U) | (unsigned char)sub)

#define GIC_IRQ_PRIORITY_GRP5SUB3_LOWEST  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 7U)
#define GIC_IRQ_PRIORITY_GRP5SUB3_HIGHEST GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 0U)

// IRQ priority levels from Lowest to highest (sub-priority 0)
#define GIC_IRQ_PRIORITY_LEVEL0_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL1_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL2_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL3_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL4_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL5_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL6_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL7_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL8_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL9_0  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL10_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL11_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL12_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL13_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL14_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL15_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL16_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL17_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL18_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL19_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL20_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL21_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL22_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL23_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL24_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL25_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL26_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL27_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL28_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL29_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 0U)
#define GIC_IRQ_PRIORITY_LEVEL30_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 0U)
//#define GIC_IRQ_PRIORITY_LEVEL31_0 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 0U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 1)
#define GIC_IRQ_PRIORITY_LEVEL0_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL1_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL2_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL3_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL4_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL5_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL6_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL7_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL8_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL9_1  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL10_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL11_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL12_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL13_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL14_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL15_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL16_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL17_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL18_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL19_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL20_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL21_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL22_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL23_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL24_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL25_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL26_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL27_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL28_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL29_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 1U)
#define GIC_IRQ_PRIORITY_LEVEL30_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 1U)
//#define GIC_IRQ_PRIORITY_LEVEL31_1 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 1U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 2)
#define GIC_IRQ_PRIORITY_LEVEL0_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL1_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL2_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL3_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL4_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL5_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL6_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL7_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL8_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL9_2  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL10_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL11_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL12_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL13_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL14_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL15_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL16_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL17_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL18_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL19_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL20_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL21_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL22_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL23_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL24_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL25_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL26_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL27_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL28_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL29_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 2U)
#define GIC_IRQ_PRIORITY_LEVEL30_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 2U)
//#define GIC_IRQ_PRIORITY_LEVEL31_2 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 2U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 3)
#define GIC_IRQ_PRIORITY_LEVEL0_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL1_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL2_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL3_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL4_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL5_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL6_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL7_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL8_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL9_3  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL10_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL11_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL12_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL13_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL14_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL15_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL16_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL17_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL18_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL19_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL20_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL21_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL22_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL23_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL24_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL25_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL26_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL27_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL28_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL29_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 3U)
#define GIC_IRQ_PRIORITY_LEVEL30_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 3U)
//#define GIC_IRQ_PRIORITY_LEVEL31_3 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 3U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 4)
#define GIC_IRQ_PRIORITY_LEVEL0_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL1_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL2_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL3_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL4_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL5_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL6_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL7_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL8_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL9_4  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL10_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL11_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL12_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL13_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL14_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL15_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL16_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL17_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL18_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL19_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL20_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL21_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL22_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL23_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL24_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL25_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL26_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL27_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL28_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL29_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 4U)
#define GIC_IRQ_PRIORITY_LEVEL30_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 4U)
//#define GIC_IRQ_PRIORITY_LEVEL31_4 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 4U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 5)
#define GIC_IRQ_PRIORITY_LEVEL0_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL1_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL2_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL3_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL4_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL5_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL6_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL7_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL8_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL9_5  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL10_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL11_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL12_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL13_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL14_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL15_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL16_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL17_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL18_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL19_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL20_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL21_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL22_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL23_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL24_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL25_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL26_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL27_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL28_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL29_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 5U)
#define GIC_IRQ_PRIORITY_LEVEL30_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 5U)
//#define GIC_IRQ_PRIORITY_LEVEL31_5 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 5U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 6)
#define GIC_IRQ_PRIORITY_LEVEL0_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL1_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL2_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL3_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL4_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL5_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL6_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL7_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL8_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL9_6  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL10_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL11_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL12_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL13_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL14_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL15_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL16_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL17_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL18_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL19_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL20_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL21_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL22_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL23_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL24_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL25_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL26_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL27_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL28_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL29_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 6U)
#define GIC_IRQ_PRIORITY_LEVEL30_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 6U)
//#define GIC_IRQ_PRIORITY_LEVEL31_6 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 6U)  // Reserved for mask condition, unusable

// IRQ priority levels from Lowest to highest (sub-priority 7)
#define GIC_IRQ_PRIORITY_LEVEL0_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 0U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL1_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 1U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL2_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 2U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL3_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 3U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL4_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 4U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL5_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 5U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL6_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 6U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL7_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 7U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL8_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 8U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL9_7  GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT( 9U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL10_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(10U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL11_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(11U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL12_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(12U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL13_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(13U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL14_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(14U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL15_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(15U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL16_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(16U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL17_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(17U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL18_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(18U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL19_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(19U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL20_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(20U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL21_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(21U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL22_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(22U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL23_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(23U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL24_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(24U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL25_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(25U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL26_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(26U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL27_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(27U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL28_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(28U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL29_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(29U, 7U)
#define GIC_IRQ_PRIORITY_LEVEL30_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(30U, 7U)
//#define GIC_IRQ_PRIORITY_LEVEL31_7 GIC_IRQ_PRIORITY_GRP5SUB3_SPLIT(31U, 7U)  // Reserved for mask condition, unusable

void irq_set_group_priority(IRQn_ID_t irqn, uint8_t grp_priority, uint8_t sub_priority);
void irq_mask(uint8_t mask);

#endif
